# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

[tool.poetry]
name = "postgresql-k8s-bundle"
version = "0.0.1-dev.0"
description = ""
authors = []
license = "Apache-2.0"
readme = "README.md"
homepage = "https://charmhub.io/postgresql-k8s-bundle"
repository = "https://github.com/canonical/postgresql-k8s-bundle"

[tool.poetry.dependencies]
python = "^3.8.10"

[tool.poetry.group.format]
optional = true

[tool.poetry.group.format.dependencies]
black = "23.9.1"
ruff = "0.0.291"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
codespell = "2.2.5"

[tool.poetry.group.integration]
optional = true

[tool.poetry.group.integration.dependencies]
pytest = "7.4.2"
pytest-operator = "0.29.0"
juju = "2.9.44.1" # Latest juju 2
tenacity = "8.2.3"
requests = "2.31.0"
lightkube = "0.14.0"
psycopg2 = {version = "2.9.7", extras = ["binary"]}

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
asyncio_mode = "auto"
markers = ["unstable"]

# Formatting tools configuration
[tool.black]
line-length = 99
target-version = ["py38"]

# Linting tools configuration
[tool.ruff]
target-version = "py38"
src = ["src", "."]
line-length = 99
select = ["A", "E", "W", "F", "C", "N", "D", "I001", "CPY001"]
extend-ignore = [
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
]
# Ignore E501 because using black creates errors with this
# Ignore D107 Missing docstring in __init__
ignore = ["E501", "D107"]

[tool.ruff.per-file-ignores]
"tests/*" = ["D100", "D101", "D102", "D103", "D104"]

[tool.ruff.flake8-copyright]
# Check for properly formatted copyright header in each file
author = "Canonical Ltd."
notice-rgx = "Copyright\\s\\d{4}([-,]\\d{4})*\\s+"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.pydocstyle]
convention = "google"
