name: bundle update available
on:
  schedule:
    - cron:  '0 */8 * * 1-5'

jobs:
  update-bundles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: check for updates
        run: |
          ./update_bundle.py releases/latest/postgresql-k8s-bundle.yaml
      - name: create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update bundles
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-bundles
          delete-branch: true
          title: 'Update Bundles'
          body: |
            Update bundles with new revisions from Charmhub.
          labels: |
            automated pr
          assignees: team-reviewers, WRFitch, marceloneppel
          reviewers: team-reviewers, marceloneppel, taurus-forever
          team-reviewers: |
            owners
            maintainers
          draft: false
